version: "3.5"

services:
  cvd-member-strapi:
    container_name: cvd-member-strapi
    image: favnyr/cvd-member-strapi
    restart: unless-stopped
    environment:
      - DATABASE_CLIENT=${DATABASE_CLIENT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - NODE_ENV=${NODE_ENV}
      - APP_KEYS=${APP_KEYS}
      - API_TOKEN_SALT=${API_TOKEN_SALT}
    links:
      - cvd-member-database:cvd-member-database
    volumes:
      - ./backend/:/opt/app/
      - ./public:/opt/app/public/uploads
    ports:
      - 1337:1337
    networks:
      - web
      - intern
    depends_on:
      - cvd-member-database
  
  cvd-member-database:
    container_name: cvd-member-database
    image: postgres:14.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - cvd-member-database-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - intern

networks:
  intern:
  web:
    external: true

volumes:
  cvd-member-database-volume: