FROM node:16

# Installing libvips-dev for sharp compatibility
#RUN apt-get update && apt-get install libvips-dev

# FIX: https://blog.dehlin.dev/docker-with-strapi-v4
# RUN apk add --no-cache libc6-compat

ARG NODE_ENV=development
ARG NODE_ENV=${NODE_ENV}
WORKDIR /opt/
COPY ./package.json ./
ENV PATH /opt/node_modules/.bin:$PATH
#RUN yarn config set network-timeout 600000 -g
RUN npm install
WORKDIR /opt/app
COPY ./ .
RUN npm run build
EXPOSE 1337

CMD ["npm", "run", "develop"]